# Generated by Django 4.1 on 2022-09-07 14:03

import accounts_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts_app.models.CustomUserManager()),
            ],
        ),
    ]
