# Generated by Django 4.1 on 2023-02-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('add_moderator', ''), ('deactivate_user', ''), ('view_report', ''), ('delete_report', '')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
