# Generated by Django 4.1 on 2023-02-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('add_moderator', 'Can add a new moderator'), ('change_moderator', 'Can change a moderator data'), ('deactivate_user', 'Can deactivate user')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
