# syntax=docker/dockerfile:1

FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apt-get update && apt-get install gettext -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && COPY requirements.txt /code/ && RUN pip install -r requirements.txt

COPY . /code/

ENTRYPOINT ["/bin/sh", "web-entrypoint.sh"]
