version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sky_library_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./SkyLibrary/app_main/.env.dev

volumes:
  db: