# Generated by Django 4.2.1 on 2023-07-15 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_moderator_task', to='media_app.media', verbose_name='media')),
                ('user_who_added', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_moderator_task', to=settings.AUTH_USER_MODEL, verbose_name='user who added')),
            ],
            options={
                'verbose_name': 'moderator task',
                'verbose_name_plural': 'moderator tasks',
                'db_table': 'staff_app_moderator_task',
            },
        ),
    ]
