# Generated by Django 4.1 on 2022-12-03 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0007_alter_media_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_moderator_task', to='media_app.media')),
                ('user_who_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_moderator_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_app_moderator_task',
            },
        ),
    ]
