# Generated by Django 4.1 on 2022-12-03 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_app', '0002_alter_moderatortask_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatortask',
            name='user_who_added',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_moderator_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
