# Generated by Django 4.1 on 2022-12-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_alter_media_active'),
        ('staff_app', '0003_alter_moderatortask_user_who_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatortask',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_moderator_task', to='media_app.media'),
        ),
    ]
