# Generated by Django 4.1 on 2022-10-12 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_who_added_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MediaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('help_text', models.CharField(max_length=80)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('user_who_added', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='media_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_app_media_tag',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_media', to='media_app.mediatags'),
        ),
    ]
