# Generated by Django 4.1 on 2022-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_media_user_who_added_mediatags_media_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tags',
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags_media', to='media_app.mediatags'),
        ),
    ]
