# Generated by Django 4.1 on 2022-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_remove_media_tags_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='tags_media', to='media_app.mediatags'),
        ),
    ]
