# Generated by Django 4.1 on 2022-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_media_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatags',
            old_name='help_text',
            new_name='help_text_en_us',
        ),
        migrations.RenameField(
            model_name='mediatags',
            old_name='name',
            new_name='name_en_us',
        ),
        migrations.AddField(
            model_name='mediatags',
            name='help_text_ru',
            field=models.CharField(default='тэг 1', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediatags',
            name='name_ru',
            field=models.CharField(default='Тэг 2', max_length=16),
            preserve_default=False,
        ),
    ]
