# Generated by Django 4.1 on 2022-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_rename_help_text_mediatags_help_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatags',
            name='help_text_en_us',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='mediatags',
            name='help_text_ru',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='mediatags',
            name='name_en_us',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='mediatags',
            name='name_ru',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
