# Generated by Django 4.1 on 2022-12-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0007_alter_media_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('target_type', models.PositiveSmallIntegerField(choices=[(1, 'Media type'), (2, 'Comment type')])),
                ('target_id', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user_who_added', models.ForeignKey(default='deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Up vote'), (-1, 'Down vote')])),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_rating', to='media_app.comment')),
                ('user_who_added', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_who_added_comment_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_app_comment_rating',
            },
        ),
    ]
