# Generated by Django 4.1.2 on 2023-01-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0008_comment_commentrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('report_type', models.PositiveSmallIntegerField(choices=[(1, 'Sexual content type'), (2, 'Spam or misleading type')])),
                ('target_type', models.PositiveSmallIntegerField(choices=[(1, 'Media type'), (2, 'Comment type')])),
                ('target_id', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user_who_added', models.ForeignKey(default='deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
