# Generated by Django 4.1.2 on 2023-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Spam or misleading'), (2, 'Offensive content'), (3, 'Sexual content'), (4, 'Violent or repulsive content'), (5, 'Harmful or dangerous acts'), (6, 'Misinformation or misleading'), (7, 'Promotes terrorism')]),
        ),
    ]
