# Generated by Django 4.1.2 on 2023-02-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0010_alter_report_content_alter_report_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AlterField(
            model_name='report',
            name='user_who_added',
            field=models.ForeignKey(default='deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_who_added_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en_us', models.CharField(max_length=16, unique=True)),
                ('name_ru', models.CharField(max_length=16, unique=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('user_who_added', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_app_report_type',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ManyToManyField(related_name='report_type_report', to='media_app.reporttype'),
        ),
    ]
