# Generated by Django 4.1.2 on 2023-02-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0011_remove_report_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='name_en_us',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='name_ru',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
