# Generated by Django 4.1 on 2023-02-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0012_alter_reporttype_name_en_us_alter_reporttype_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('change_content_field_to_banned', 'Can change the content of the comment to "This comment was banned"')]},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('change_active_field', 'Can change the value of the active field')]},
        ),
    ]
