# Generated by Django 4.1 on 2023-02-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0013_alter_comment_options_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('change_comment_content_field_to_banned', 'Can change the content of the comment to "This comment was banned"')]},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('change_media_active_field', 'Can change the value of the active field')]},
        ),
    ]
