# Generated by Django 4.1 on 2023-02-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0014_alter_comment_options_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('change_media_active_field', 'Can change the value of the media active field')]},
        ),
    ]
