# Generated by Django 4.2.1 on 2023-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0015_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('change_comment_content_field_to_banned', 'Can change the content of the comment to "This comment was banned"')], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commentrating',
            options={'verbose_name': 'comment rating', 'verbose_name_plural': 'comment ratings'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('change_media_active_field', 'Can change the value of the media active field')], 'verbose_name': 'media', 'verbose_name_plural': 'medias'},
        ),
        migrations.AlterModelOptions(
            name='mediadownload',
            options={'verbose_name': 'media download', 'verbose_name_plural': 'media downloads'},
        ),
        migrations.AlterModelOptions(
            name='mediarating',
            options={'verbose_name': 'media rating', 'verbose_name_plural': 'media ratings'},
        ),
        migrations.AlterModelOptions(
            name='mediatags',
            options={'verbose_name': 'media tag', 'verbose_name_plural': 'media tags'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name': 'report type', 'verbose_name_plural': 'report types'},
        ),
    ]
