# Generated by Django 4.2.1 on 2023-05-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0017_alter_comment_content_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_report', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
    ]
