# Generated by Django 4.2.1 on 2023-05-15 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0018_alter_comment_user_who_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_comment_rating', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_media', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='mediadownload',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_media_download', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='mediarating',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_added_media_rating', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='mediatags',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tags', to=settings.AUTH_USER_MODEL, verbose_name='user who added'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='user_who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_type', to=settings.AUTH_USER_MODEL, verbose_name='user who addded'),
        ),
    ]
