# Generated by Django 4.2.1 on 2023-06-04 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0019_alter_commentrating_user_who_added_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediarating',
            unique_together={('media', 'user_who_added')},
        ),
    ]
