# Generated by Django 4.2.1 on 2023-07-13 15:21

import app_main.s3_storage
from django.db import migrations, models
import media_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0020_alter_mediarating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(storage=app_main.s3_storage.MediaStorage(), upload_to=media_app.models.get_file_upload, verbose_name='file'),
        ),
    ]
